### ISSUE TITLE
Problem in colab notebooks

### ISSUE THREAD

**Issue by amrzv** [deepmind/PGMax#1]
Hi.
When running notebooks in colab, for example [rcn.ipynb](https://colab.research.google.com/github/deepmind/PGMax/blob/main/examples/rcn.ipynb), there is a problem in the installation cell:
![image](https://user-images.githubusercontent.com/36787333/216316367-6e01176f-2571-46a7-95a4-689aecbdc7cd.png)
This is because `!cd PGMax` works locally and not globally.
Solution: replace this line to `%cd PGMax`
P.S: I can make PR for this.

**Comment by antoine-dedieu** [comment]
Thank you for letting us know! 
This issue is now fixed
