### ISSUE TITLE
Installation seems to be broken

### ISSUE THREAD

**Issue by NishanthJKumar** [deepmind/PGMax#5]
I just attempted to install PGMax via pip: i.e. `pip install pgmax`. While it did work, I noticed that it didn't seem to install any of the dependencies. Indeed, when I opened up a terminal and ran `from pgmax import fgraph`, I got a `ModuleNotFoundError: No module named 'jax'`.

The core issue seems to be that there are no requirements listed in the `setup.py` file, and the `requirements.txt` file is also not linked to `setup.py` in any way (indeed, [this commit](https://github.com/deepmind/PGMax/commit/af4b40b74fd85deb4bdff3a609ce0d4ad04e1549) seems to have removed the link between `setup.py` and `requirements.txt`). If I clone the repo and run `pip install -r requirements.txt`, then things work fine, but the `pip` installation does still seem currently broken.

**Comment by StannisZhou** [comment]
Thanks for raising the issue! This should have been fixed by the new 0.6.1 release
